model:
    multiscale:
        multiscale_input_channel: 3
        multiscale_output_channel: 1
    cross_attention:
        att_type: "soft_att"
    seq2vec:
        arch: skipthoughts
        dir_st: E:\Python\tools\skipthoughts
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    fusion:
        correct_local_hidden_dim: 512
        correct_local_hidden_drop: 0.2
        supplement_global_hidden_dim: 512
        supplement_global_hidden_drop: 0.2
        dynamic_fusion_dim: 1024
        dynamic_fusion_drop: 0.1
        mca_DROPOUT_R: 0.1
        mca_HIDDEN_SIZE: 512
        mca_FF_SIZE: 1024
        mca_MULTI_HEAD: 8
        mca_HIDDEN_SIZE_HEAD: 64
    embed:
        embed_dim: 512
    name: GaLR
dataset:
    datatype: rsicd
    data_split:
    data_path: 'data/rsicd_precomp/'
    image_path: '../MTFN-RR-PyTorch-Code-master/data/sydney_precomp/images/'
    vocab_path: 'vocab/rsicd_splits_vocab.json'
    local_path: './detection/representation/SYDNEY/sydney_local.npy'
    batch_size: 10
    batch_size_val: 10
    workers: 0
optim:
    epochs: 3
    lr: 0.0001
    lr_decay_param: 0.7
    lr_update_epoch: 20
    grad_clip: 0
    max_violation: 0
    margin: 0.2
    resume: False
logs:
    eval_step: 1
    print_freq: 10
    ckpt_save_path: "checkpoint/"
    logger_name: 'logs/'
k_fold:
    experiment_name: 'sydney_GaLR'
    nums: 3
    current_num: 0
